from enum import Enum

class IncidentType(str, Enum):
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    HIGH_CPU = "HIGH_CPU"
    DISK_FULL = "DISK_FULL"
    MEMORY_LEAK = "MEMORY_LEAK"
    NETWORK_ISSUE = "NETWORK_ISSUE"
    SERVICE_DOWN = "SERVICE_DOWN"
    SECURITY_BREACH = "SECURITY_BREACH"
    DATA_CORRUPTION = "DATA_CORRUPTION"
    API_FAILURE = "API_FAILURE"
    DEPLOYMENT_FAILURE = "DEPLOYMENT_FAILURE"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    OTHER = "OTHER"

class IncidentSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"

class IncidentStatus(str, Enum):
    RECEIVED = "RECEIVED"
    CLASSIFYING = "CLASSIFYING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"

class VoiceProcessingStatus(str, Enum):
    RECEIVED = "RECEIVED"
    DOWNLOADING = "DOWNLOADING"
    TRANSCRIBING = "TRANSCRIBING"
    PROCESSED = "PROCESSED"
    ERROR = "ERROR"
    DUPLICATE = "DUPLICATE"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
